# Generated by Django 4.2.6 on 2023-11-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('acc', models.CharField(max_length=200)),
                ('gst_in', models.CharField(max_length=200)),
                ('price_type', models.CharField(max_length=200)),
                ('gst_type', models.CharField(max_length=200)),
            ],
        ),
    ]
